### ISSUE TITLE
64 character limit imposed by lambda_function_arn even if full ARN is given

### ISSUE THREAD

**Issue by jonmer85** [pjodouin/ansible-repo#1]
The 64 character limitation is imposed even if the full Lambda ARN is given. Per AWS docs, the full ARN must be less than 140 characters - http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

The quick fix is to defer the check until after it is identified that the name is not an ARN.

**Comment by pjodouin** [comment]
Thanks @jonmer85.  Sorry for the delayed response but issue is fixed now.

Thanks for pointing this out!
